services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm-gateway
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - ~/apps/litellm/litellm_config.yaml:/app/config.yaml:ro
    tmpfs:
      - /app/logs:size=64M,mode=1777
    env_file:
      - .env
    # ports:
    #   - "4000:4000"
    mem_limit: 256m
    environment:
      - LITELLM_CONFIG_PATH=/app/config.yaml
    networks:
      - nginxproxymanager

networks:
  nginxproxymanager:
    external: true