name: file-nexus-prod
services:
  temporal-proxy:
    image: alpine/socat
    container_name: temporal-proxy
    mem_limit: 64m
    networks:
      - nginxproxymanager
    env_file:
      - .env
    restart: unless-stopped
    command: TCP4-LISTEN:7233,fork,reuseaddr SOCKS5:tailscale:${TEMPORAL_SERVER_DOMAIN}:${TEMPORAL_SERVER_PORT},socksport=1055

  file-nexus:
    container_name: file-nexus
    depends_on:
      - temporal-proxy
    mem_limit: 512m
    image: thatssatyadocker/file-nexus:latest
    env_file:
      - .env
    networks:
      - nginxproxymanager
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ping", "-c", "2", "100.100.100.100"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      - "autoheal=true"

networks:
  nginxproxymanager:
    name: nginxproxymanager
    external: true
