name: file-nexus-prod
services:
  file-nexus:
    container_name: file-nexus
    mem_limit: 512m
    image: thatssatyadocker/file-nexus:latest
    env_file:
      - .env
    network_mode: container:tailscale
    # network_mode: host
    restart: always
    healthcheck:
      test: ["CMD", "ping", "-c", "4", "100.100.100.100"]
      interval: 10s
      timeout: 5s
      retries: 3
    labels:
      - "autoheal=true"
