name: tailscale
services:
  network-holder:
    image: alpine:latest
    container_name: network-holder
    command: tail -f /dev/null
    restart: always
    mem_limit: 20mb
    hostname: tailscale
    networks:
      - nginxproxymanager

  tailscale:
    depends_on:
      - network-holder
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
      - SYS_ADMIN
    cpu_shares: 50
    container_name: tailscale
    network_mode: container:network-holder
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: "134217728"
    environment:
      - TS_ACCEPT_DNS=true
      - TS_AUTHKEY=
      - TS_EXTRA_ARGS=--advertise-exit-node=true --ssh --accept-routes --advertise-tags=tag:pifive-container-gateway
      - TS_HOSTNAME=pifive-tailscale
      # - TS_ROUTES=
      - TS_SERVE_CONFIG=/usr/tailscale/config/serve.json
      - TS_STATE_DIR=/var/lib/tailscale
    image: tailscale/tailscale:latest
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Tailscale/icon.png
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/tailscale
        target: /var/lib/tailscale
      - type: bind
        source: /dev/net/tun
        target: /dev/net/tun
      - type: bind
        source: ${HOME}/apps/pifive-tailscale/config
        target: /usr/tailscale/config

  tailscale-services-advertiser:
    depends_on:
      - tailscale
    image: docker:cli
    restart: always
    command: >
      sh -c '
        echo "Waiting for tailscale container to be ready..."
        until docker exec tailscale tailscale status > /dev/null 2>&1; do
          sleep 5
        done
        echo "Tailscale is ready."

        if [ -n "$$RAW_SERVICES" ]; then
          echo "Found services to advertise using RAW_SERVICES variable."
          # Remove single/double quotes and replace commas with spaces
          CLEAN_SERVICES=$$(echo "$$RAW_SERVICES" | tr -d "\047\042" | tr "," " ")
          
          for SERVICE in $$CLEAN_SERVICES; do
            if [ -z "$$SERVICE" ]; then continue; fi
            echo "Advertising service: $$SERVICE"
            docker exec tailscale tailscale serve advertise "svc:$$SERVICE" || echo "Failed to advertise $$SERVICE"
          done
        else
          echo "No RAW_SERVICES provided."
        fi

        echo "Advertisement process finished. Staying alive..."
        tail -f /dev/null
      '
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    networks:
      - nginxproxymanager

networks:
  nginxproxymanager:
    name: nginxproxymanager
    external: true
