services:
  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    restart: always
    mem_limit: 100mb
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
